export enum IpcEvents {
  LOAD_MEDIA_METADATA = 'LOAD_MEDIA_METADATA',
  DOWNLOAD = 'DOWNLOAD',
  CANCEL_DOWNLOAD = 'CANCEL_DOWNLOAD',
  DOWNLOAD_OUTPUT = 'DOWNLOAD_OUTPUT',
  // DOWNLOAD_PROGRESS = 'DOWNLOAD_PROGRESS',
  DOWNLOAD_STOPPED = 'DOWNLOAD_STOPPED',
}
