export enum IpcEvents {
  SEARCH_MEDIA = 'SEARCH_MEDIA',
  DOWNLOAD = 'DOWNLOAD',
  CANCEL_DOWNLOAD = 'CANCEL_DOWNLOAD',
  DOWNLOAD_OUTPUT = 'DOWNLOAD_OUTPUT',
  // DOWNLOAD_PROGRESS = 'DOWNLOAD_PROGRESS',
  DOWNLOAD_STOPPED = 'DOWNLOAD_STOPPED',
}
